# Generated by Django 5.1.4 on 2025-01-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
